CategoryCreatedSuccess = "Category created successfully"
CategoryDeleteSuccess = "Category removed successfully"
CouldNotReadImage = "Could not proccess your image, plasea try again with a new image"
Email = "Invalid Email address"
ErrCategoryNotExists = "That category dose not exist"
ErrorFailedLogin = "Username or Password incorrect"
ErrorGenericBadRequest = "Your request doe not match the specified format, please fix and try again"
ErrorGenericInternal = "We encountred an error proccessing you're request, please try again later"
ErrorUserNotExists = "No user with that name has been found"
NotPngOrJpeg = "Profile Picture must be a PNG or a JPG"
Required = "This field is required"
SuccessUpdateProfilePicture = "Profile Picture Updated Successfully"
SuccessUserDelete = "User deleted successfully"
SuccessUserUpdate = "User info update successfully"
UserUpdateSuccess = "User info updated successfully"

[ErrorDuplicateEmailOrUsername]
one = "Email or Username Already Exists"
other = "Email or Username Already Exists"
