[CouldNotReadImage]
hash = "sha1-9830ddecde6551eeabd42378e8628f763ed69744"
other = "Could not proccess your image, plasea try again with a new image"

[Email]
hash = "sha1-205ea7dbce5f6d59418f5c720699b13238b1517f"
other = "Invalid Email address"

[ErrorDuplicateEmailOrUsername]
few = "Email or Username Already Exists"
hash = "sha1-318d66d4626db63687c21e0790d4305b017bc15c"
many = "Email or Username Already Exists"
one = "Email or Username Already Exists"
other = "Email or Username Already Exists"
two = "Email or Username Already Exists"
zero = "Email or Username Already Exists"

[ErrorFailedLogin]
hash = "sha1-7b2d4d8c0ab1d9e166d7f8488fe1f7aee6971c91"
other = "Username or Password incorrect"

[ErrorGenericInternal]
hash = "sha1-9de6a795c79f1d7c4f8f5ab9ce1db26f5e70be52"
other = "We encountred an error proccessing you're request, please try again later"

[ErrorUserNotExists]
hash = "sha1-1030932b66074803de9f40c75b4d9af54a5ecdd8"
other = "No user with that name has been found"

[InvalidEmail]
hash = "sha1-a88b7dcd1a9e3e17770bbaa6d7515b31a2d7e85d"
other = "email"

[NotPngOrJpeg]
hash = "sha1-d80efd8a9fcb8dd5e39efdd3e7e31b00c0f43f06"
other = "Profile Picture must be a PNG or a JPG"

[Required]
hash = "sha1-dedbaded6d5a4ed17eefa2e4ee3eee026b7d1d11"
other = "This field is required"

[SuccessUpdateProfilePicture]
hash = "sha1-aa2842aeff9f2835ce5dfa096fb320ba4a3660fd"
other = "Profile Picture Updated Successfully"

[SuccessUserDelete]
hash = "sha1-c73f99152b03acd45e1d3e08021cd9c2029e9743"
other = "User deleted successfully"

[SuccessUserUpdate]
hash = "sha1-534b7dc859a23ce2fe7ff68eaba93c940c391119"
other = "User info update successfully"

[UnhashedPassword]
hash = "sha1-5baa61e4c9b93f3f0682250b6cf8331b7ee68fd8"
other = "password"
